---
jobs:
- name: run-get-iplayer
  public: true
  serial: true
  plan:
  - get: get-iplayer-config
  - get: get-iplayer-scheduler
  - task: run-get-iplayer
    file: get-iplayer-scheduler/ci/run-get-iplayer.yml
    params:
      DO_TOKEN: ((do_token))
      SSH_KEY_ID: ((ssh_key_id)) 
      RSA_KEY: ((private_rsa_key))
  - put: get-iplayer-config

resources:

- name: get-iplayer-config
  type: git
  source:
    uri: git@github.com:danhigham/get_iplayer_config.git
    private_key: ((private_rsa_key))
    branch: master

- name: get-iplayer-scheduler 
  type: git
  source:
    uri: https://github.com/danhigham/iplayer-scheduler.git 
    branch: master

