---
jobs:
- name: run-get-iplayer
  public: true
  serial: true
  plan:
  - get: get-iplayer-config
  - get: get-iplayer-scheduler
  - task: run-get-iplayer
    file: get-iplayer-scheduler/ci/run-get-iplayer.yml
  - put: get-iplayer-config

resources:

- name: get-iplayer-config
  type: git
  source:
    uri: https://github.com/danhigham/get_iplayer_config
    branch: master

- name: get-iplayer-scheduler 
  type: git
  source:
    uri: https://github.com/danhigham/iplayer-scheduler.git 
    branch: master

