---
jobs:
- name: run-get-iplayer
  public: true
  serial: true
  plan:
  - get: go-time
    trigger: true
  - get: get-iplayer-config
  - get: get-iplayer-scheduler
  - task: run-get-iplayer
    file: get-iplayer-scheduler/ci/run-get-iplayer.yml
    params:
      DO_TOKEN: ((do_token))
      SSH_KEY_ID: ((ssh_key_id)) 
      RSA_KEY: ((private_rsa_key))
  - put: get-iplayer-config
    params: { repository: "get-iplayer-config" }
  - put: plex-rsync
    params: { "sync_dir" : "iplayer_incoming" }

resource_types:
- name: rsync-resource
  type: docker-image
  source:
    repository: danhigham/concourse-rsync-resource
    tag: latest

resources:

- name: go-time
  type: time
  source:
    start: 1:00 AM
    location: America/Los_Angeles

- name: plex-rsync
  type: rsync-resource
  source:
    server: 192.168.10.5
    base_dir: :Plex\ Media/BBC
    user: ((rsync_user))
    private_key: ((private_rsa_key))
    disable_version_path: true

- name: get-iplayer-config
  type: git
  source:
    uri: git@github.com:danhigham/get_iplayer_config.git
    private_key: ((private_rsa_key))
    branch: master

- name: get-iplayer-scheduler 
  type: git
  source:
    uri: https://github.com/danhigham/iplayer-scheduler.git 
    branch: master

